Support the OpenJDK stdlib for all tests

diff --git a/acceptance-tests b/acceptance-tests
--- a/acceptance-tests
+++ b/acceptance-tests
@@ -15,10 +15,9 @@ for test in tests/*; do
     #	continue
     #fi
 	DIR=`mktemp -d -t tvm-tests-XXXXXXX` || (echo "Failed to create tmp directory"; exit 1)
-	javac -bootclasspath stdlib:$RT -d $DIR $test/*.java || (echo "Failed to compile"; exit 1)
+	javac -d $DIR $test/*.java || (echo "Failed to compile"; exit 1)
 	find stdlib -type f -name '*.java' | xargs javac -d $DIR || (echo "Failed to compile"; exit 1)
-	find stdlib -type f -name '*.class' | xargs -I{} -n1 cp {} $DIR/
-	diff <(find $DIR -type f | xargs tvm) $test/out
+	diff <(find $DIR -type f | xargs tvm stdlib ) $test/out
 	if [[ $? -eq 0 ]]; then
 		echo -e "\033[32mPASS\033[0m"
 	else
