real string support

diff --git a/acceptance-tests b/acceptance-tests
--- a/acceptance-tests
+++ b/acceptance-tests
@@ -2,12 +2,15 @@
 
 set -e
 
+RT="/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/rt.jar"
+
 go install ./...
 go test ./...
 
 for test in tests/*; do
 	echo "Running $test"
 	DIR=`mktemp -d -t tvm-tests-XXXXXXX` || (echo "Failed to create tmp directory"; exit 1)
-	javac -d $DIR $test/*.java || (echo "Failed to compile"; exit 1)
-	diff <(tvm ${DIR}/*) $test/out
+	javac -bootclasspath stdlib:$RT -d $DIR $test/*.java || (echo "Failed to compile"; exit 1)
+	find stdlib -type f -name '*.java' | xargs javac -d $DIR || (echo "Failed to compile"; exit 1)
+	diff <(find $DIR -type f | xargs tvm) $test/out
 done
