added ability to handle multiple class files

diff --git a/acceptance-tests b/acceptance-tests
--- a/acceptance-tests
+++ b/acceptance-tests
@@ -5,9 +5,9 @@ set -e
 go install ./...
 go test ./...
 
-for f in tests/*.java; do
-	echo "Running $f"
+for test in tests/*; do
+	echo "Running $test"
 	DIR=`mktemp -d -t tvm-tests-XXXXXXX` || (echo "Failed to create tmp directory"; exit 1)
-	javac -d $DIR $f || (echo "Failed to compile"; exit 1)
-	diff <(tvm ${DIR}/*) tests/`basename -s ".java" $f`.out
+	javac -d $DIR $test/*.java || (echo "Failed to compile"; exit 1)
+	diff <(tvm ${DIR}/*) $test/out
 done
